spring:
  main:
    log-startup-info: off
    banner-mode: off
  sql:
    init:
      mode: always
      schema-location: classpath:schema.sql
      data-location: classpath:data.sql
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driver-class-name: org.h2.Driver
logging:
  level:
    root: INFO
    ru.yandex.practicum.filmorate: INFO
    org.zalando.logbook: TRACE
logbook:
  format:
    style: http
